config/routes.rb
Rails.application.routes.draw do
  resources :sales
  post 'sales/import', to: 'sales#import'
  root to: "sales#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/sale.rb
class Sale < ApplicationRecord
  def Sale.import_file(file)
    file_content = file.read.force_encoding("UTF-8")
    file_array = file_content.lines.map { |line| line.split("\t") }
    file_array.each_with_index do |item, index|
      if index > 0
        @sale = Sale.new
        @sale.buyer = item[0]
        @sale.description= item[1]
        @sale.unit_price= item[2]
        @sale.amount= item[3]
        @sale.address= item[4]
        @sale.provider= item[5]
        @sale.save
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  before_action :set_sale, only: %i[ show edit update destroy ]

  # GET /sales or /sales.json
  def index
    @sales = Sale.all
  end

  # GET /sales/1 or /sales/1.json
  def show
  end

  def import
    begin
      uploaded_file = params[:file]
      Sale.import_file(uploaded_file)
      redirect_to sales_url, notice: "Os arquivos foram importados com Sucesso."
    end
  end

  # GET /sales/new
  def new
    @sale = Sale.new
  end

  # GET /sales/1/edit
  def edit
  end

  # POST /sales or /sales.json
  def create
    @sale = Sale.new(sale_params)

    respond_to do |format|
      if @sale.save
        format.html { redirect_to @sale, notice: "Sale was successfully created." }
        format.json { render :show, status: :created, location: @sale }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sales/1 or /sales/1.json
  def update
    respond_to do |format|
      if @sale.update(sale_params)
        format.html { redirect_to @sale, notice: "Sale was successfully updated." }
        format.json { render :show, status: :ok, location: @sale }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sales/1 or /sales/1.json
  def destroy
    @sale.destroy
    respond_to do |format|
      format.html { redirect_to sales_url, notice: "Sale was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sale
      @sale = Sale.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def sale_params
      params.require(:sale).permit(:buyer, :description, :unit_price, :amount, :address, :provider)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NamaTest</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/sales/_form.html.erb
<div class="form-container">
  <%= form_with(model: sale) do |form|%>
    <% if sale.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(sale.errors.count, "error") %> prohibited this sale from being saved:</h2>

        <ul>
          <% sale.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= form.label 'Comprador' %>
      <%= form.text_area :buyer %>
    </div>

    <div class="field">
      <%= form.label 'Descrição' %>
      <%= form.text_area :description %>
    </div>

    <div class="field">
      <%= form.label 'Preço Unitário' %>
      <%= form.text_field :unit_price %>
    </div>

    <div class="field">
      <%= form.label 'Quantidade' %>
      <%= form.text_field :amount %>
    </div>

    <div class="field">
      <%= form.label 'Endereço' %>
      <%= form.text_area :address %>
    </div>

    <div class="field">
      <%= form.label 'Fornecedor' %>
      <%= form.text_field :provider %>
    </div>

    <div class="actions">
      <%= button_tag 'Salvar' %>
    </div>
  <% end %>
</div>

app/views/sales/edit.html.erb
<h1>Editar</h1>

<%= render 'form', sale: @sale %>
<br>
<div class="form-footer">
  <%= link_to 'Exibir', @sale, class: 'show_btn' %> <br>
  <%= link_to 'Voltar', sales_path, class: 'delete_btn' %>
</div>

app/views/sales/index.html.erb
<p id="notice"><%= notice %></p>

<%= form_tag '/sales/import', :multipart => true do %>
  <label for="file">Suba aqui seu arquivo de texto</label> <%= file_field_tag "file",  required: true %>
  <%= submit_tag "Importar" %>
<% end %>

<table>
  <thead>
    <tr>
      <th>Comprador</th>
      <th>Descrição</th>
      <th>Preço Unitário</th>
      <th>Quantidade</th>
      <th>Endereço</th>
      <th>Fornecedor</th>
      <th colspan="3">Ações</th>
    </tr>
  </thead>

  <tbody>
    <% @sales.each do |sale| %>
      <tr>
        <td><%= sale.buyer %></td>
        <td><%= sale.description %></td>
        <td class="col-center"><%= number_to_currency(sale.unit_price, unit: "R$", separator: ",", delimiter: "") %></td>
        <td class="col-center"><%= sale.amount %></td>
        <td><%= sale.address %></td>
        <td><%= sale.provider %></td>
        <td class="col-center"><%= link_to 'Exibir', sale , class: 'show_btn'%></td>
        <td class="col-center"><%= link_to 'Editar', edit_sale_path(sale) , class: 'edit_btn' %></td>
        <td class="col-center"><%= link_to 'Excluir', sale,class: 'delete_btn', method: :delete, data: { confirm: 'Tem certeza disso?' } %></td>
      </tr>
    <% end %>

  </tbody>
  <tfoot>
  <tr>
    <td colspan="9">Receita bruta total: <%= number_to_currency(@sales.sum('unit_price * amount'), unit: "R$", separator: ",", delimiter: "") %></td>
  </tr>
  </tfoot>
</table>

<br>

<%= link_to 'Novo Registro', new_sale_path %>

app/views/sales/new.html.erb
<h1>Novo</h1>

<%= render 'form', sale: @sale %>

<div class="form-footer">
  <%= link_to 'Voltar', sales_path, class: 'delete_btn'%>
</div>

app/views/sales/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Comprador:</strong>
  <%= @sale.buyer %>
</p>

<p>
  <strong>Descrição:</strong>
  <%= @sale.description %>
</p>

<p>
  <strong>Preço Unitário:</strong>
  <%= @sale.unit_price %>
</p>

<p>
  <strong>Quantidade:</strong>
  <%= @sale.amount %>
</p>

<p>
  <strong>Endereço:</strong>
  <%= @sale.address %>
</p>

<p>
  <strong>Fornecedor:</strong>
  <%= @sale.provider %>
</p>

<%= link_to 'Editar', edit_sale_path(@sale) %> <br>
<%= link_to 'Voltar', sales_path %>